// <auto-generated />
using System;
using HospitalSystemDAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HospitalSystemDAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251019172054_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HospitalSystemDAL.Entites.Clinic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("openingHours")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Clinics");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Downtown Clinic",
                            openingHours = "9 AM - 5 PM"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Uptown Clinic",
                            openingHours = "10 AM - 6 PM"
                        });
                });

            modelBuilder.Entity("HospitalSystemDAL.Entites.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ClinicId")
                        .HasColumnType("int");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Specialty")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClinicId");

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Nasr City, Cairo",
                            ClinicId = 1,
                            Gender = "M",
                            Name = "Dr. Ahmed Hassan",
                            Specialty = "Cardiology",
                            phoneNumber = "01098765432"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Heliopolis, Cairo",
                            ClinicId = 1,
                            Gender = "F",
                            Name = "Dr. Mona Ibrahim",
                            Specialty = "Dermatology",
                            phoneNumber = "01055555555"
                        });
                });

            modelBuilder.Entity("HospitalSystemDAL.Entites.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Salary")
                        .HasColumnType("float");

                    b.Property<string>("phoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Dokki, Giza",
                            Gender = "F",
                            Name = "Heba Ali",
                            Position = "Receptionist",
                            Salary = 7500.0,
                            phoneNumber = "01044444444"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Cairo",
                            Gender = "M",
                            Name = "Khaled Hassan",
                            Position = "Accountant",
                            Salary = 9000.0,
                            phoneNumber = "01033333333"
                        });
                });

            modelBuilder.Entity("HospitalSystemDAL.Entites.Patient", b =>
                {
                    b.Property<int>("PatientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PatientId"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PatientId");

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            PatientId = 1,
                            Address = "Giza, Egypt",
                            DateOfBirth = new DateTime(1995, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = "F",
                            Name = "Sara Mohamed",
                            phoneNumber = "01011122334"
                        },
                        new
                        {
                            PatientId = 2,
                            Address = "Maadi, Cairo",
                            DateOfBirth = new DateTime(1990, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = "M",
                            Name = "Omar Khaled",
                            phoneNumber = "01099998888"
                        });
                });

            modelBuilder.Entity("HospitalSystemDAL.Entites.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClinicId")
                        .HasColumnType("int");

                    b.Property<int?>("DoctorId")
                        .HasColumnType("int");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int?>("PatientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReservationDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ClinicId");

                    b.HasIndex("DoctorId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("PatientId");

                    b.ToTable("Reservations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClinicId = 1,
                            DoctorId = 1,
                            EmployeeId = 1,
                            PatientId = 1,
                            ReservationDate = new DateTime(2025, 10, 21, 20, 20, 54, 473, DateTimeKind.Local).AddTicks(2879)
                        },
                        new
                        {
                            Id = 2,
                            ClinicId = 1,
                            DoctorId = 2,
                            EmployeeId = 2,
                            PatientId = 2,
                            ReservationDate = new DateTime(2025, 10, 22, 20, 20, 54, 473, DateTimeKind.Local).AddTicks(2919)
                        });
                });

            modelBuilder.Entity("HospitalSystemDAL.Entites.Doctor", b =>
                {
                    b.HasOne("HospitalSystemDAL.Entites.Clinic", "Clinic")
                        .WithMany("Doctors")
                        .HasForeignKey("ClinicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clinic");
                });

            modelBuilder.Entity("HospitalSystemDAL.Entites.Reservation", b =>
                {
                    b.HasOne("HospitalSystemDAL.Entites.Clinic", "Clinic")
                        .WithMany("Reservations")
                        .HasForeignKey("ClinicId");

                    b.HasOne("HospitalSystemDAL.Entites.Doctor", "Doctor")
                        .WithMany("Reservations")
                        .HasForeignKey("DoctorId");

                    b.HasOne("HospitalSystemDAL.Entites.Employee", "Employee")
                        .WithMany("Reservations")
                        .HasForeignKey("EmployeeId");

                    b.HasOne("HospitalSystemDAL.Entites.Patient", "Patient")
                        .WithMany("Reservations")
                        .HasForeignKey("PatientId");

                    b.Navigation("Clinic");

                    b.Navigation("Doctor");

                    b.Navigation("Employee");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("HospitalSystemDAL.Entites.Clinic", b =>
                {
                    b.Navigation("Doctors");

                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("HospitalSystemDAL.Entites.Doctor", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("HospitalSystemDAL.Entites.Employee", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("HospitalSystemDAL.Entites.Patient", b =>
                {
                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
